// <auto-generated />
using System;
using DBlog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBlog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240722181813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DBlog.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://image.shutterstock.com/image-vector/design-seamless-advertising-pattern-creative-600w-112354688.jpg",
                            PublishedDate = new DateTime(2024, 7, 22, 21, 18, 12, 930, DateTimeKind.Local).AddTicks(8859),
                            Title = "First Article",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://fatstacksblog.com/wp-content/uploads/2019/11/Person-writing-article-nov26.jpg",
                            PublishedDate = new DateTime(2024, 7, 22, 21, 18, 12, 930, DateTimeKind.Local).AddTicks(8870),
                            Title = "Second Article",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://leverageedublog.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2020/01/24145013/article-writing.jpg",
                            PublishedDate = new DateTime(2024, 7, 22, 21, 18, 12, 930, DateTimeKind.Local).AddTicks(8872),
                            Title = "Third Article",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://th.bing.com/th/id/OIP.WwajPSJu5YunOsdTaD0hqwHaE7?rs=1&pid=ImgDetMain",
                            PublishedDate = new DateTime(2024, 7, 22, 21, 18, 12, 930, DateTimeKind.Local).AddTicks(8873),
                            Title = "Fourth Article",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://image.shutterstock.com/image-vector/design-seamless-advertising-pattern-creative-600w-112354688.jpg",
                            PublishedDate = new DateTime(2024, 7, 22, 21, 18, 12, 930, DateTimeKind.Local).AddTicks(8875),
                            Title = "Fifth Article",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://fatstacksblog.com/wp-content/uploads/2019/11/Person-writing-article-nov26.jpg",
                            PublishedDate = new DateTime(2024, 7, 22, 21, 18, 12, 930, DateTimeKind.Local).AddTicks(8876),
                            Title = "Sixth Article",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DBlog.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DBlog.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "user1@example.com",
                            IsAdmin = false,
                            UserName = "User1"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "user2@example.com",
                            IsAdmin = false,
                            UserName = "User2"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "user3@example.com",
                            IsAdmin = false,
                            UserName = "User3"
                        });
                });

            modelBuilder.Entity("DBlog.Models.Article", b =>
                {
                    b.HasOne("DBlog.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBlog.Models.User", null)
                        .WithMany("Articles")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBlog.Models.Comment", b =>
                {
                    b.HasOne("DBlog.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBlog.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBlog.Models.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DBlog.Models.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
