// <auto-generated />
using System;
using DBlog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBlog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DBlog.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://image.shutterstock.com/image-vector/design-seamless-advertising-pattern-creative-600w-112354688.jpg",
                            PublishedDate = new DateTime(2024, 7, 23, 1, 31, 29, 915, DateTimeKind.Local).AddTicks(8038),
                            Title = "First Article"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://fatstacksblog.com/wp-content/uploads/2019/11/Person-writing-article-nov26.jpg",
                            PublishedDate = new DateTime(2024, 7, 23, 1, 31, 29, 915, DateTimeKind.Local).AddTicks(8050),
                            Title = "Second Article"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://leverageedublog.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2020/01/24145013/article-writing.jpg",
                            PublishedDate = new DateTime(2024, 7, 23, 1, 31, 29, 915, DateTimeKind.Local).AddTicks(8051),
                            Title = "Third Article"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://www.staceyeburke.com/wp-content/uploads/2018/06/publications1.jpg",
                            PublishedDate = new DateTime(2024, 7, 23, 1, 31, 29, 915, DateTimeKind.Local).AddTicks(8053),
                            Title = "Fourth Article"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://image.shutterstock.com/image-vector/design-seamless-advertising-pattern-creative-600w-112354688.jpg",
                            PublishedDate = new DateTime(2024, 7, 23, 1, 31, 29, 915, DateTimeKind.Local).AddTicks(8054),
                            Title = "Fifth Article"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageUrl = "https://fatstacksblog.com/wp-content/uploads/2019/11/Person-writing-article-nov26.jpg",
                            PublishedDate = new DateTime(2024, 7, 23, 1, 31, 29, 915, DateTimeKind.Local).AddTicks(8055),
                            Title = "Sixth Article"
                        });
                });

            modelBuilder.Entity("DBlog.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DBlog.Models.Comment", b =>
                {
                    b.HasOne("DBlog.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("DBlog.Models.Article", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
