// <auto-generated />
using System;
using DBlog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBlog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("DBlog.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFile")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageFile = "/img/1.jpg",
                            PublishedDate = new DateTime(2024, 7, 14, 17, 30, 18, 47, DateTimeKind.Local).AddTicks(796),
                            Title = "First Article"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageFile = "/img/6.jpg",
                            PublishedDate = new DateTime(2024, 6, 4, 17, 30, 18, 47, DateTimeKind.Local).AddTicks(809),
                            Title = "Second Article"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageFile = "/img/4.jpg",
                            PublishedDate = new DateTime(2024, 5, 5, 17, 30, 18, 47, DateTimeKind.Local).AddTicks(810),
                            Title = "Third Article"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageFile = "/img/7.jpg",
                            PublishedDate = new DateTime(2024, 6, 4, 17, 30, 18, 47, DateTimeKind.Local).AddTicks(811),
                            Title = "Fourth Article"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageFile = "/img/5.jpg",
                            PublishedDate = new DateTime(2024, 6, 24, 17, 30, 18, 47, DateTimeKind.Local).AddTicks(813),
                            Title = "Fifth Article"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
                            ImageFile = "/img/6.jpg",
                            PublishedDate = new DateTime(2024, 7, 4, 17, 30, 18, 47, DateTimeKind.Local).AddTicks(814),
                            Title = "Sixth Article"
                        });
                });

            modelBuilder.Entity("DBlog.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DBlog.Models.Comment", b =>
                {
                    b.HasOne("DBlog.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("DBlog.Models.Article", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
